export const orderData = [
  {
    id: 1,
    orderStatus: "Новый",
    deliveryMethod: "Быстрая доставка",
    orderPrice: "1 840 000",
    img: "../img/png/orderImg.png",
    status: "new",
    orderNumber: 1242,
  },
  {
    id: 2,
    orderStatus: "Принят",
    deliveryMethod: "Стандартная доставка",
    orderPrice: "1 840 000",
    img: "../img/png/orderImg.png",
    status: "accepted",
    orderNumber: 1243,
  },
  {
    id: 3,
    orderStatus: "Выполнен",
    deliveryMethod: "Бесплатная доставка",
    orderPrice: "1 840 000",
    img: "../img/png/orderImg.png",
    status: "completed",
    orderNumber: 1244,
  },
  {
    id: 4,
    orderStatus: "Отменен",
    deliveryMethod: "Бесплатная доставка",
    orderPrice: "1 840 000",
    img: "../img/png/orderImg.png",
    status: "cancel",
    orderNumber: 1245,
  },
];
